"""initial schema

Revision ID: 6918a468329b
Revises: 
Create Date: 2026-08-20 23:57:10.995960
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6918a468329b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_api_key_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('node_id', sa.Uuid(), nullable=True),
    sa.Column('vps_id', sa.Uuid(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_created_action', 'audit_logs', ['created_at', 'action'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_table('images',
    sa.Column('alias', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('os_family', sa.String(length=48), nullable=False),
    sa.Column('version', sa.String(length=48), nullable=False),
    sa.Column('architecture', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('source_remote', sa.String(length=64), nullable=False),
    sa.Column('source_identifier', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('size_mb', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('min_cpu', sa.Integer(), nullable=False),
    sa.Column('min_ram_mb', sa.Integer(), nullable=False),
    sa.Column('min_disk_gb', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images')),
    sa.UniqueConstraint('alias', name=op.f('uq_images_alias'))
    )
    op.create_table('log_entries',
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('node_id', sa.Uuid(), nullable=True),
    sa.Column('vps_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_entries'))
    )
    op.create_index(op.f('ix_log_entries_created_at'), 'log_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_log_entries_node_id'), 'log_entries', ['node_id'], unique=False)
    op.create_index(op.f('ix_log_entries_severity'), 'log_entries', ['severity'], unique=False)
    op.create_index(op.f('ix_log_entries_source'), 'log_entries', ['source'], unique=False)
    op.create_index(op.f('ix_log_entries_user_id'), 'log_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_log_entries_vps_id'), 'log_entries', ['vps_id'], unique=False)
    op.create_index('ix_logs_created_source', 'log_entries', ['created_at', 'source'], unique=False)
    op.create_table('node_metric_samples',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('mem_used_mb', sa.Float(), nullable=True),
    sa.Column('mem_total_mb', sa.Float(), nullable=True),
    sa.Column('storage_used_gb', sa.Float(), nullable=True),
    sa.Column('storage_total_gb', sa.Float(), nullable=True),
    sa.Column('net_rx_bps', sa.Float(), nullable=True),
    sa.Column('net_tx_bps', sa.Float(), nullable=True),
    sa.Column('load1', sa.Float(), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_metric_samples'))
    )
    op.create_index('ix_nodemetrics_node_ts', 'node_metric_samples', ['node_id', 'ts'], unique=False)
    op.create_table('nodes',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('public_ip', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('credential_hash', sa.String(length=128), nullable=True),
    sa.Column('credential_encrypted', sa.Text(), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_version', sa.String(length=32), nullable=True),
    sa.Column('lxd_version', sa.String(length=32), nullable=True),
    sa.Column('os_name', sa.String(length=120), nullable=True),
    sa.Column('os_version', sa.String(length=120), nullable=True),
    sa.Column('kernel_version', sa.String(length=120), nullable=True),
    sa.Column('architecture', sa.String(length=32), nullable=True),
    sa.Column('cpu_model', sa.String(length=255), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('ram_total_mb', sa.BigInteger(), nullable=True),
    sa.Column('storage_total_gb', sa.Float(), nullable=True),
    sa.Column('storage_driver', sa.String(length=32), nullable=True),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('ram_used_mb', sa.BigInteger(), nullable=True),
    sa.Column('storage_used_gb', sa.Float(), nullable=True),
    sa.Column('load1', sa.Float(), nullable=True),
    sa.Column('uptime_seconds', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nodes')),
    sa.UniqueConstraint('name', name=op.f('uq_nodes_name'))
    )
    op.create_index(op.f('ix_nodes_status'), 'nodes', ['status'], unique=False)
    op.create_table('security_events',
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=True),
    sa.Column('vps_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_events'))
    )
    op.create_index(op.f('ix_security_events_category'), 'security_events', ['category'], unique=False)
    op.create_index(op.f('ix_security_events_created_at'), 'security_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_security_events_node_id'), 'security_events', ['node_id'], unique=False)
    op.create_index(op.f('ix_security_events_severity'), 'security_events', ['severity'], unique=False)
    op.create_index(op.f('ix_security_events_user_id'), 'security_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_security_events_vps_id'), 'security_events', ['vps_id'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('totp_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vps_metric_samples',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('vps_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('mem_used_mb', sa.Float(), nullable=True),
    sa.Column('mem_total_mb', sa.Float(), nullable=True),
    sa.Column('swap_used_mb', sa.Float(), nullable=True),
    sa.Column('disk_used_gb', sa.Float(), nullable=True),
    sa.Column('disk_total_gb', sa.Float(), nullable=True),
    sa.Column('disk_read_bps', sa.Float(), nullable=True),
    sa.Column('disk_write_bps', sa.Float(), nullable=True),
    sa.Column('net_rx_bps', sa.Float(), nullable=True),
    sa.Column('net_tx_bps', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vps_metric_samples'))
    )
    op.create_index('ix_vpsmetrics_vps_ts', 'vps_metric_samples', ['vps_id', 'ts'], unique=False)
    op.create_table('api_keys',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=24), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_api_keys_key_hash'))
    )
    op.create_index(op.f('ix_api_keys_prefix'), 'api_keys', ['prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('enrollment_tokens',
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name=op.f('fk_enrollment_tokens_node_id_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollment_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_enrollment_tokens_token_hash'))
    )
    op.create_index(op.f('ix_enrollment_tokens_node_id'), 'enrollment_tokens', ['node_id'], unique=False)
    op.create_table('ip_addresses',
    sa.Column('node_id', sa.Uuid(), nullable=True),
    sa.Column('family', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('cidr', sa.Integer(), nullable=True),
    sa.Column('gateway', sa.String(length=128), nullable=True),
    sa.Column('reverse_dns', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('vps_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name=op.f('fk_ip_addresses_node_id_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ip_addresses')),
    sa.UniqueConstraint('address', name=op.f('uq_ip_addresses_address'))
    )
    op.create_index(op.f('ix_ip_addresses_node_id'), 'ip_addresses', ['node_id'], unique=False)
    op.create_index(op.f('ix_ip_addresses_status'), 'ip_addresses', ['status'], unique=False)
    op.create_index(op.f('ix_ip_addresses_vps_id'), 'ip_addresses', ['vps_id'], unique=False)
    op.create_table('networks',
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ipv4_subnet', sa.String(length=64), nullable=True),
    sa.Column('ipv6_subnet', sa.String(length=128), nullable=True),
    sa.Column('ipv4_gateway', sa.String(length=64), nullable=True),
    sa.Column('managed', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name=op.f('fk_networks_node_id_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_networks'))
    )
    op.create_index(op.f('ix_networks_node_id'), 'networks', ['node_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_tokens_token_hash'))
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('storage_pools',
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('driver', sa.String(length=32), nullable=False),
    sa.Column('total_gb', sa.Float(), nullable=True),
    sa.Column('used_gb', sa.Float(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name=op.f('fk_storage_pools_node_id_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_storage_pools'))
    )
    op.create_index(op.f('ix_storage_pools_node_id'), 'storage_pools', ['node_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_sessions_token_hash'))
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('vps',
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('image_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('provider_ref', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cpu_limit', sa.Integer(), nullable=False),
    sa.Column('ram_mb', sa.Integer(), nullable=False),
    sa.Column('swap_mb', sa.Integer(), nullable=False),
    sa.Column('disk_gb', sa.Integer(), nullable=False),
    sa.Column('process_limit', sa.Integer(), nullable=False),
    sa.Column('ipv4', sa.String(length=64), nullable=True),
    sa.Column('ipv6', sa.String(length=128), nullable=True),
    sa.Column('mac_address', sa.String(length=32), nullable=True),
    sa.Column('network_name', sa.String(length=64), nullable=True),
    sa.Column('dns_servers', sa.JSON(), nullable=False),
    sa.Column('ssh_keys', sa.JSON(), nullable=False),
    sa.Column('password_auth_enabled', sa.Boolean(), nullable=False),
    sa.Column('root_password_set', sa.Boolean(), nullable=False),
    sa.Column('privileged', sa.Boolean(), nullable=False),
    sa.Column('raw_config', sa.JSON(), nullable=False),
    sa.Column('provision_error', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_vps_image_id_images')),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name=op.f('fk_vps_node_id_nodes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_vps_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vps')),
    sa.UniqueConstraint('provider_ref', name=op.f('uq_vps_provider_ref'))
    )
    op.create_index(op.f('ix_vps_node_id'), 'vps', ['node_id'], unique=False)
    op.create_index('ix_vps_node_status', 'vps', ['node_id', 'status'], unique=False)
    op.create_index(op.f('ix_vps_owner_id'), 'vps', ['owner_id'], unique=False)
    op.create_index('ix_vps_owner_status', 'vps', ['owner_id', 'status'], unique=False)
    op.create_index(op.f('ix_vps_status'), 'vps', ['status'], unique=False)
    op.create_table('backups',
    sa.Column('vps_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('optimized_storage', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['vps_id'], ['vps.id'], name=op.f('fk_backups_vps_id_vps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backups'))
    )
    op.create_index(op.f('ix_backups_created_at'), 'backups', ['created_at'], unique=False)
    op.create_index(op.f('ix_backups_node_id'), 'backups', ['node_id'], unique=False)
    op.create_index(op.f('ix_backups_status'), 'backups', ['status'], unique=False)
    op.create_index(op.f('ix_backups_vps_id'), 'backups', ['vps_id'], unique=False)
    op.create_table('snapshots',
    sa.Column('vps_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stateful', sa.Boolean(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['vps_id'], ['vps.id'], name=op.f('fk_snapshots_vps_id_vps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snapshots'))
    )
    op.create_index(op.f('ix_snapshots_created_at'), 'snapshots', ['created_at'], unique=False)
    op.create_index('ix_snapshots_vps_created', 'snapshots', ['vps_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_snapshots_vps_id'), 'snapshots', ['vps_id'], unique=False)
    op.create_table('volumes',
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('vps_id', sa.Uuid(), nullable=True),
    sa.Column('pool_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('volume_type', sa.String(length=24), nullable=False),
    sa.Column('size_gb', sa.Float(), nullable=True),
    sa.Column('used_gb', sa.Float(), nullable=True),
    sa.Column('mount_point', sa.String(length=255), nullable=True),
    sa.Column('read_only', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name=op.f('fk_volumes_node_id_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pool_id'], ['storage_pools.id'], name=op.f('fk_volumes_pool_id_storage_pools')),
    sa.ForeignKeyConstraint(['vps_id'], ['vps.id'], name=op.f('fk_volumes_vps_id_vps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volumes'))
    )
    op.create_index(op.f('ix_volumes_node_id'), 'volumes', ['node_id'], unique=False)
    op.create_index(op.f('ix_volumes_vps_id'), 'volumes', ['vps_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volumes_vps_id'), table_name='volumes')
    op.drop_index(op.f('ix_volumes_node_id'), table_name='volumes')
    op.drop_table('volumes')
    op.drop_index(op.f('ix_snapshots_vps_id'), table_name='snapshots')
    op.drop_index('ix_snapshots_vps_created', table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_created_at'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_backups_vps_id'), table_name='backups')
    op.drop_index(op.f('ix_backups_status'), table_name='backups')
    op.drop_index(op.f('ix_backups_node_id'), table_name='backups')
    op.drop_index(op.f('ix_backups_created_at'), table_name='backups')
    op.drop_table('backups')
    op.drop_index(op.f('ix_vps_status'), table_name='vps')
    op.drop_index('ix_vps_owner_status', table_name='vps')
    op.drop_index(op.f('ix_vps_owner_id'), table_name='vps')
    op.drop_index('ix_vps_node_status', table_name='vps')
    op.drop_index(op.f('ix_vps_node_id'), table_name='vps')
    op.drop_table('vps')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_storage_pools_node_id'), table_name='storage_pools')
    op.drop_table('storage_pools')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_networks_node_id'), table_name='networks')
    op.drop_table('networks')
    op.drop_index(op.f('ix_ip_addresses_vps_id'), table_name='ip_addresses')
    op.drop_index(op.f('ix_ip_addresses_status'), table_name='ip_addresses')
    op.drop_index(op.f('ix_ip_addresses_node_id'), table_name='ip_addresses')
    op.drop_table('ip_addresses')
    op.drop_index(op.f('ix_enrollment_tokens_node_id'), table_name='enrollment_tokens')
    op.drop_table('enrollment_tokens')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_prefix'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index('ix_vpsmetrics_vps_ts', table_name='vps_metric_samples')
    op.drop_table('vps_metric_samples')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_index(op.f('ix_security_events_vps_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_user_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_severity'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_node_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_created_at'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_category'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_nodes_status'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index('ix_nodemetrics_node_ts', table_name='node_metric_samples')
    op.drop_table('node_metric_samples')
    op.drop_index('ix_logs_created_source', table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_vps_id'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_user_id'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_source'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_severity'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_node_id'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_created_at'), table_name='log_entries')
    op.drop_table('log_entries')
    op.drop_table('images')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('ix_audit_created_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
