#!/usr/bin/env bash
# CVX Node Agent installer.
#
# One-command usage (recommended — command is generated by the panel):
#   curl -fsSL https://<panel>/install/node | sudo bash -s -- \
#     --token <ONE_TIME_TOKEN> --control-plane https://<panel>
#
# Env-var style still works:
#   sudo CVX_ENROLL_TOKEN=... CVX_CONTROL_PLANE=... bash cvx-install.sh
#   sudo bash cvx-install.sh uninstall
#
# The installer stages downloads to disk, verifies the agent archive against
# the control plane's published SHA-256, runs the agent as a dedicated
# unprivileged system account, and prints a detection checklist.
set -u

CVX_USER="cvx-agent"
INSTALL_ROOT="/opt/cvx-agent"
ETC_ROOT="/etc/cvx-agent"
VENV="$INSTALL_ROOT/venv"

log()  { printf '✓ %s\n' "$*"; }
warn() { printf '! %s\n' "$*" >&2; }
die()  { printf '× %s\n' "$*" >&2; exit 1; }

require_root() {
  [ "$(id -u)" -eq 0 ] || die "must run as root (try: curl ... | sudo bash)"
}

parse_args() {
  CVX_ENROLL_TOKEN="${CVX_ENROLL_TOKEN:-}"
  CVX_CONTROL_PLANE="${CVX_CONTROL_PLANE:-}"
  LOCAL_SRC=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --token)          CVX_ENROLL_TOKEN="${2:-}"; shift 2 ;;
      --control-plane)  CVX_CONTROL_PLANE="${2:-}"; shift 2 ;;
      --local)          LOCAL_SRC="${2:-}"; shift 2 ;;
      uninstall)        shift ;;
      *) warn "unknown argument: $1"; shift ;;
    esac
  done
}

validate_inputs() {
  [ -n "$CVX_ENROLL_TOKEN" ] || die "enrollment token missing (--token or CVX_ENROLL_TOKEN)"
  case "$CVX_ENROLL_TOKEN" in
    cvxenroll_*) : ;;
    *) die "token does not look like a CVX enrollment token" ;;
  esac
  [ -n "$CVX_CONTROL_PLANE" ] || die "control-plane URL missing (--control-plane or CVX_CONTROL_PLANE)"
  case "$CVX_CONTROL_PLANE" in
    https://*|http://localhost*|http://127.0.0.1*) : ;;
    http://*) die "refusing plain-HTTP control plane (use HTTPS)" ;;
    *) die "control plane must be an https:// URL" ;;
  esac
}

detect_system() {
  [ "$(uname -s)" = "Linux" ] || die "unsupported OS: $(uname -s)"
  ARCH="$(uname -m)"
  log "Linux detected ($ARCH)"
  command -v systemctl >/dev/null 2>&1 || die "systemd is required to run the agent service"
  log "systemd detected"
  if command -v lxd >/dev/null 2>&1 || command -v incus >/dev/null 2>&1; then
    LXD_BIN="$(command -v lxd || command -v incus)"
    log "LXD detected ($($LXD_BIN version 2>/dev/null | head -1))"
  else
    LXD_BIN=""
    warn "LXD not found — will be installed"
  fi
}

install_lxd() {
  if [ -n "$LXD_BIN" ]; then return 0; fi
  if command -v snap >/dev/null 2>&1; then
    snap install lxd || die "snap install lxd failed"
  else
    apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq lxd \
      || die "could not install LXD (snap/apt both unavailable)"
  fi
  LXD_BIN="$(command -v lxd || command -v incus)" || die "LXD installed but binary not found"
  if ! $LXD_BIN storage list >/dev/null 2>&1; then
    $LXD_BIN init --auto || die "lxd init failed"
  fi
  log "LXD ready ($($LXD_BIN version 2>/dev/null | head -1))"
}

stage_agent_archive() {
  mkdir -p "$INSTALL_ROOT"
  if [ -n "$LOCAL_SRC" ]; then
    rm -rf "$INSTALL_ROOT.tmp"
    cp -r "$LOCAL_SRC" "$INSTALL_ROOT.tmp"
    rm -rf "$INSTALL_ROOT.tmp/.git"
    mv "$INSTALL_ROOT.tmp" "${INSTALL_ROOT}.new"
    log "agent code staged from $LOCAL_SRC"
    return 0
  fi
  TARBALL_URL="${CVX_AGENT_TARBALL_URL:-$CVX_CONTROL_PLANE/downloads/cvx-agent-latest.tar.gz}"
  TMP_TGZ="$(mktemp)"
  TMP_SUM="$(mktemp)"
  # Staged download: fetch to temp files first, verify integrity, then extract.
  curl -fsSL "$TARBALL_URL" -o "$TMP_TGZ" || die "agent download failed: $TARBALL_URL"
  if curl -fsSL "$TARBALL_URL.sha256" -o "$TMP_SUM" 2>/dev/null && [ -s "$TMP_SUM" ]; then
    EXPECTED="$(awk '{print $1}' "$TMP_SUM" | tr -d '\r')"
    ACTUAL="$(sha256sum "$TMP_TGZ" | awk '{print $1}')"
    [ "$EXPECTED" = "$ACTUAL" ] || { rm -f "$TMP_TGZ" "$TMP_SUM"; die "checksum mismatch for agent archive"; }
    log "archive checksum verified"
  else
    warn "no checksum published by control plane — skipping verification"
  fi
  rm -rf "${INSTALL_ROOT}.new"
  mkdir -p "${INSTALL_ROOT}.new"
  tar -xzf "$TMP_TGZ" -C "${INSTALL_ROOT}.new" --strip-components=1 \
    || { rm -f "$TMP_TGZ"; die "agent archive extraction failed"; }
  rm -f "$TMP_TGZ" "$TMP_SUM"
  mv "${INSTALL_ROOT}.new" "${INSTALL_ROOT}.staged"
  log "agent code staged"
}

install_python() {
  command -v python3 >/dev/null 2>&1 || apt-get update -qq
  command -v python3 >/dev/null 2>&1 || die "python3 required"
  python3 -m venv "$VENV" 2>/dev/null || { apt-get install -y -qq python3-venv || die "python3-venv required"; python3 -m venv "$VENV"; }
  "$VENV/bin/pip" install --quiet --upgrade pip
  "$VENV/bin/pip" install --quiet "$INSTALL_ROOT.staged" || die "pip install of agent failed"
  ln -sf "$VENV/bin/cvx-agent" /usr/local/bin/cvx-agent
  rm -rf "$INSTALL_ROOT.old"
  [ -d "$INSTALL_ROOT" ] && mv "$INSTALL_ROOT" "$INSTALL_ROOT.old"
  mv "$INSTALL_ROOT.staged" "$INSTALL_ROOT"
  rm -rf "$INSTALL_ROOT.old"
  log "agent installed into venv"
}

create_account() {
  if id "$CVX_USER" >/dev/null 2>&1; then
    log "system account exists ($CVX_USER)"
  else
    useradd --system --shell /usr/sbin/nologin --home "$ETC_ROOT" "$CVX_USER" \
      || die "could not create system account"
    log "created system account ($CVX_USER)"
  fi
  # LXD socket access for the unprivileged agent account.
  if [ -S /var/snap/lxd/common/lxd/unix.socket ]; then
    SOCK_GRP=$(stat -c '%G' /var/snap/lxd/common/lxd/unix.socket 2>/dev/null || echo lxd)
    getent group "$SOCK_GRP" >/dev/null || SOCK_GRP=lxd
    usermod -aG "$SOCK_GRP" "$CVX_USER" 2>/dev/null || true
  elif [ -S /var/lib/lxd/unix.socket ]; then
    usermod -aG lxd "$CVX_USER" 2>/dev/null || true
  fi
}

write_unit() {
  cat > /etc/systemd/system/cvx-agent.service <<UNIT
[Unit]
Description=CVX Node Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${CVX_USER}
Group=${CVX_USER}
ExecStart=${VENV}/bin/cvx-agent serve
Restart=always
RestartSec=5
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
ReadWritePaths=${ETC_ROOT} /var/lib/lxd /var/snap/lxd
Umask=077

[Install]
WantedBy=multi-user.target
UNIT
  systemctl daemon-reload
  systemctl enable cvx-agent.service >/dev/null 2>&1 || true
  log "systemd service installed"
}

enroll() {
  umask 077
  mkdir -p "$ETC_ROOT"
  printf '%s\n' "control_plane: $CVX_CONTROL_PLANE" > "$ETC_ROOT/config.yaml"
  chmod 600 "$ETC_ROOT/config.yaml"
  chown -R "$CVX_USER:$CVX_USER" "$ETC_ROOT"
  umask 022
  if [ -s "$ETC_ROOT/credential" ]; then
    log "existing credential found — skipping enrollment"
    return 0
  fi
  local out
  out=$("$VENV/bin/cvx-agent" enroll --control-plane "$CVX_CONTROL_PLANE" --token "$CVX_ENROLL_TOKEN" 2>&1) \
    || { echo "$out" >&2; die "enrollment rejected by control plane"; }
  chown -R "$CVX_USER:$CVX_USER" "$ETC_ROOT"
  chmod 600 "$ETC_ROOT/credential" 2>/dev/null || true
  log "node enrolled"
}

start_service() {
  systemctl restart cvx-agent.service || die "service failed to start"
  sleep 2
  systemctl is-active --quiet cvx-agent.service || {
    journalctl -u cvx-agent.service -n 30 --no-pager >&2
    die "cvx-agent.service is not active"
  }
  log "agent service running"
}

uninstall() {
  require_root
  systemctl stop cvx-agent.service 2>/dev/null || true
  systemctl disable cvx-agent.service 2>/dev/null || true
  rm -f /etc/systemd/system/cvx-agent.service
  systemctl daemon-reload
  rm -rf "$INSTALL_ROOT" "$VENV"
  warn "uninstalled (kept $ETC_ROOT — remove manually if desired)"
  exit 0
}

main() {
  require_root
  if [ "${1:-}" = "uninstall" ]; then
    uninstall
  fi
  parse_args "$@"
  validate_inputs
  detect_system
  install_lxd
  stage_agent_archive
  install_python
  create_account
  enroll
  write_unit
  start_service
  echo ""
  echo "NODE READY — this node is enrolled with CVX."
}

main "$@"
